# 日志配置
logging:
  level: "info"      # 日志级别: debug, info, warn, error, fatal
  format: "text"     # 日志格式: text, json
  file: ""   # 日志文件路径，为空则输出到控制台
  isTerminal: true
grpc_url: "https://solana-yellowstone-grpc.publicnode.com:443"

#转账监控配置
transfer_monitor_enable: true # 是否启用转账监控

#监控转账来源地址

transfer_source_address: ["5tzFkiKscXHK5ZXCGbXZxdw7gTjjD1mBwuoFbhUvuAi9","ASTyfSima4LLAdDgoFGkgqoKowG1LZFDr9fAQrg7iaJZ"]
